server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/qaapp
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB

openai.api.key=YOUR_API_KEY